services:
  # Pyongyang Simulated Devices
  py-router:
    image: alpine:latest
    container_name: pyu-py-router
    hostname: pyu-py-router
    networks:
      - kafka_pyu-main
    command: sh -c "while true; do sleep 3600; done"

  py-switch:
    image: alpine:latest
    container_name: pyu-py-switch
    hostname: pyu-py-switch
    networks:
      - kafka_pyu-main
    command: sh -c "while true; do sleep 3600; done"

  py-server:
    image: nginx:alpine
    container_name: pyu-py-server
    hostname: pyu-py-server
    networks:
      - kafka_pyu-main

networks:
  kafka_pyu-main:
    external: true

#Jose Vasconcelos - Dec 2025
#GitHub - KariocaMarron
#acme5bataj10@outlook.com
